### ISSUE TITLE
Brain structure shown together with cells or colorcoded cells based on where they are

### ISSUE THREAD

**Issue by tang37** [wildrootlab/sharcc#14]
Hello,

Thank you for developing a nice program! I wonder if brain structure could be added to the brain wireframe so that where the cells reside could be visualized. Alternatively, I wonder if color-coded cells based on where they reside in could be implemented in the brain wireframe plot.

Thanks!
Yu

**Comment by tang37** [comment]
Never mind, just saw that it is implemented in the plotting code.

**Comment by tang37** [comment]
Never mind, just saw that it is implemented in the plotting code.

**Comment by Virginia9733** [comment]
May I ask how can I color coded two population of cells? I manually labeled them seperately in FIJI via Cell Counter, but not sure how to get the two different colors to distinguish the populations? As shown here:

<img width="1200" height="1116" alt="Image" src="https://github.com/user-attachments/assets/669fc53d-0bfb-48e4-ac20-84bd95d37f9a" />

<img width="1903" height="1002" alt="Image" src="https://github.com/user-attachments/assets/9f474be3-b723-4378-a9ef-be645ee9f735" />

Any suggestions or hints are appreciated!
