### ISSUE TITLE
All works great until I try to analyze section with an atlas

### ISSUE THREAD

**Issue by kcaplan99** [wildrootlab/sharcc#7]
I'm able to get through all the steps great until I reach part 4 "Analyze Section with Allen Atlas/Chon Data". These are the errors I'm getting:

Error using textscan
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in loadCCFtoFP (line 10)
titles = textscan(fid, '%s%s%s%s%s%s', 1, 'delimiter', ',');

Error in Analyze_ROIs (line 55)
    CCFtoFPtable = loadCCFtoFP(CCF_to_FP_location);

Error in SHARCQ/AnalyzeSectionwithAllenAtlasButtonPushed (line 123)
            [fig, app.roiLocation, app.roiAnnotation] =
            Analyze_ROIs(app.imageFolder,name,app.annotationVolumeLocation,app.structureTreeLocation,app.plane,true,app.chonImages,app.CCFtoFP); 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 410)
Error while evaluating Button PrivateButtonPushedFcn.

I'd love to be able to use this, so any help would be greatly appreciated!

**Comment by krislauridsen** [comment]
Thanks for writing about your issue! The first question I have is, which atlas are you attempting to analyze your data with? The Allen atlas or the Chon updated Franklin-Paxinos one? Additionally, have you downloaded all of the 'Chon data' files and stored them locally on your computer in the correct directory?

Thanks

**Comment by kcaplan99** [comment]
Thanks for responding! I’ve tried both the Allen and Chon, same error. I made sure to follow GitHub instructions to a T for both atlases (downloaded all the files and put in their respective folders within the SHARCQ folder.

**Comment by krislauridsen** [comment]
From what your error indicates it seems like it is unable to find a certain file that it needs. Could you just confirm for me that this is what your 'Chon' directory looks like?
<img width="479" alt="image" src="https://user-images.githubusercontent.com/84092983/174903317-cec40f3c-9d85-44e8-b64d-fa35fa917638.png">

**Comment by kcaplan99** [comment]
Oooh I just realized it was because I forgot to take all of the contents out of the Chon folder i downloaded. It works great now! Thank you!!

**Comment by winkyfong** [comment]
Thank you so much! I've been encountering the same problem and finally solved the problem after following your instructions!
